-- 테이블이 존재할 경우 삭제
DROP TABLE IF EXISTS app_version;
DROP TABLE IF EXISTS keep_song;
DROP TABLE IF EXISTS song_info;
DROP TABLE IF EXISTS artist;
DROP TABLE IF EXISTS keep_list;
DROP TABLE IF EXISTS member;
DROP TABLE IF EXISTS comment;
DROP TABLE IF EXISTS comment_like;
DROP TABLE IF EXISTS report;
DROP TABLE IF EXISTS song_review;
DROP TABLE IF EXISTS song_review_option;

-- member 테이블 생성
CREATE TABLE IF NOT EXISTS member (
    member_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    nickname VARCHAR(255),
    email VARCHAR(50) NOT NULL,
    gender VARCHAR(20),
    birthyear INT,
    provider VARCHAR(20) NOT NULL,
    UNIQUE(email, provider), -- 이메일과 제공자는 유니크하도록 설정
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL
);

-- keepList 테이블 생성
CREATE TABLE IF NOT EXISTS keep_list (
    keep_list_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    member_id BIGINT NOT NULL,
    keep_name VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL
);

-- artistInfo 테이블 생성
CREATE TABLE IF NOT EXISTS artist (
    artist_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    artist_name VARCHAR(255) NOT NULL,
    artist_type VARCHAR(100),
    related_artists TEXT,
    country VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL
);


-- songInfo 테이블 생성
CREATE TABLE IF NOT EXISTS song_info (
    song_info_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    song_name VARCHAR(255) NOT NULL,
    artist_id BIGINT,
    artist_name VARCHAR(255) NOT NULL,
    artist_type VARCHAR(100),
    related_artists TEXT,
    country VARCHAR(255),
    album VARCHAR(255),
    song_number INT NOT NULL,
    octave VARCHAR(10),
    tj_link VARCHAR(255),
    tags VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL
);

-- keepSong 테이블 생성
CREATE TABLE IF NOT EXISTS keep_song (
    keep_song_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    keep_list_id BIGINT NOT NULL,
    song_info_id BIGINT NOT NULL,
    song_number INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL
);

-- appVersion 테이블 생성
CREATE TABLE IF NOT EXISTS app_version (
    app_version_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    platform VARCHAR(10) NOT NULL,
    version VARCHAR(20) NOT NULL,
    force_update BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS song_review_option (
    song_review_option_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS song_review (
    song_review_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    song_info_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    song_review_option_id BIGINT NOT NULL,
    gender VARCHAR(20),
    birthyear INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS comment (
    comment_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    parent_comment_id BIGINT,
    song_info_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    content TEXT,
    is_recomment BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
);

ALTER TABLE comment
    ADD CONSTRAINT fk_member_id
        FOREIGN KEY (member_id) REFERENCES member(member_id)
            ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE IF NOT EXISTS comment_like (
    comment_like_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    comment_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS report (
    report_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    comment_id BIGINT NOT NULL,
    reporter_member_id BIGINT NOT NULL,
    subject_member_id BIGINT NOT NULL,
    report_reason VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL
);