// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package mysql

var TableNames = struct {
	AppVersion       string
	Artist           string
	Comment          string
	CommentLike      string
	KeepList         string
	KeepSong         string
	Member           string
	Report           string
	SongTempInfo     string
	SongInfo         string
	SongReview       string
	SongReviewOption string
}{
	AppVersion:       "app_version",
	Artist:           "artist",
	Comment:          "comment",
	CommentLike:      "comment_like",
	KeepList:         "keep_list",
	KeepSong:         "keep_song",
	Member:           "member",
	Report:           "report",
	SongTempInfo:     "songTempInfo",
	SongInfo:         "song_info",
	SongReview:       "song_review",
	SongReviewOption: "song_review_option",
}
