// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package mysql

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// MemberDeviceToken is an object representing the database table.
type MemberDeviceToken struct {
	MemberDeviceTokenID int64     `boil:"member_device_token_id" json:"member_device_token_id" toml:"member_device_token_id" yaml:"member_device_token_id"`
	MemberID            int64     `boil:"member_id" json:"member_id" toml:"member_id" yaml:"member_id"`
	DeviceToken         string    `boil:"device_token" json:"device_token" toml:"device_token" yaml:"device_token"`
	IsActivate          null.Bool `boil:"is_activate" json:"is_activate,omitempty" toml:"is_activate" yaml:"is_activate,omitempty"`
	CreatedAt           null.Time `boil:"created_at" json:"created_at,omitempty" toml:"created_at" yaml:"created_at,omitempty"`
	UpdatedAt           null.Time `boil:"updated_at" json:"updated_at,omitempty" toml:"updated_at" yaml:"updated_at,omitempty"`
	DeletedAt           null.Time `boil:"deleted_at" json:"deleted_at,omitempty" toml:"deleted_at" yaml:"deleted_at,omitempty"`

	R *memberDeviceTokenR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L memberDeviceTokenL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var MemberDeviceTokenColumns = struct {
	MemberDeviceTokenID string
	MemberID            string
	DeviceToken         string
	IsActivate          string
	CreatedAt           string
	UpdatedAt           string
	DeletedAt           string
}{
	MemberDeviceTokenID: "member_device_token_id",
	MemberID:            "member_id",
	DeviceToken:         "device_token",
	IsActivate:          "is_activate",
	CreatedAt:           "created_at",
	UpdatedAt:           "updated_at",
	DeletedAt:           "deleted_at",
}

var MemberDeviceTokenTableColumns = struct {
	MemberDeviceTokenID string
	MemberID            string
	DeviceToken         string
	IsActivate          string
	CreatedAt           string
	UpdatedAt           string
	DeletedAt           string
}{
	MemberDeviceTokenID: "member_device_token.member_device_token_id",
	MemberID:            "member_device_token.member_id",
	DeviceToken:         "member_device_token.device_token",
	IsActivate:          "member_device_token.is_activate",
	CreatedAt:           "member_device_token.created_at",
	UpdatedAt:           "member_device_token.updated_at",
	DeletedAt:           "member_device_token.deleted_at",
}

// Generated where

var MemberDeviceTokenWhere = struct {
	MemberDeviceTokenID whereHelperint64
	MemberID            whereHelperint64
	DeviceToken         whereHelperstring
	IsActivate          whereHelpernull_Bool
	CreatedAt           whereHelpernull_Time
	UpdatedAt           whereHelpernull_Time
	DeletedAt           whereHelpernull_Time
}{
	MemberDeviceTokenID: whereHelperint64{field: "`member_device_token`.`member_device_token_id`"},
	MemberID:            whereHelperint64{field: "`member_device_token`.`member_id`"},
	DeviceToken:         whereHelperstring{field: "`member_device_token`.`device_token`"},
	IsActivate:          whereHelpernull_Bool{field: "`member_device_token`.`is_activate`"},
	CreatedAt:           whereHelpernull_Time{field: "`member_device_token`.`created_at`"},
	UpdatedAt:           whereHelpernull_Time{field: "`member_device_token`.`updated_at`"},
	DeletedAt:           whereHelpernull_Time{field: "`member_device_token`.`deleted_at`"},
}

// MemberDeviceTokenRels is where relationship names are stored.
var MemberDeviceTokenRels = struct {
	Member string
}{
	Member: "Member",
}

// memberDeviceTokenR is where relationships are stored.
type memberDeviceTokenR struct {
	Member *Member `boil:"Member" json:"Member" toml:"Member" yaml:"Member"`
}

// NewStruct creates a new relationship struct
func (*memberDeviceTokenR) NewStruct() *memberDeviceTokenR {
	return &memberDeviceTokenR{}
}

func (r *memberDeviceTokenR) GetMember() *Member {
	if r == nil {
		return nil
	}
	return r.Member
}

// memberDeviceTokenL is where Load methods for each relationship are stored.
type memberDeviceTokenL struct{}

var (
	memberDeviceTokenAllColumns            = []string{"member_device_token_id", "member_id", "device_token", "is_activate", "created_at", "updated_at", "deleted_at"}
	memberDeviceTokenColumnsWithoutDefault = []string{"member_id", "device_token", "deleted_at"}
	memberDeviceTokenColumnsWithDefault    = []string{"member_device_token_id", "is_activate", "created_at", "updated_at"}
	memberDeviceTokenPrimaryKeyColumns     = []string{"member_device_token_id"}
	memberDeviceTokenGeneratedColumns      = []string{}
)

type (
	// MemberDeviceTokenSlice is an alias for a slice of pointers to MemberDeviceToken.
	// This should almost always be used instead of []MemberDeviceToken.
	MemberDeviceTokenSlice []*MemberDeviceToken
	// MemberDeviceTokenHook is the signature for custom MemberDeviceToken hook methods
	MemberDeviceTokenHook func(context.Context, boil.ContextExecutor, *MemberDeviceToken) error

	memberDeviceTokenQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	memberDeviceTokenType                 = reflect.TypeOf(&MemberDeviceToken{})
	memberDeviceTokenMapping              = queries.MakeStructMapping(memberDeviceTokenType)
	memberDeviceTokenPrimaryKeyMapping, _ = queries.BindMapping(memberDeviceTokenType, memberDeviceTokenMapping, memberDeviceTokenPrimaryKeyColumns)
	memberDeviceTokenInsertCacheMut       sync.RWMutex
	memberDeviceTokenInsertCache          = make(map[string]insertCache)
	memberDeviceTokenUpdateCacheMut       sync.RWMutex
	memberDeviceTokenUpdateCache          = make(map[string]updateCache)
	memberDeviceTokenUpsertCacheMut       sync.RWMutex
	memberDeviceTokenUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var memberDeviceTokenAfterSelectHooks []MemberDeviceTokenHook

var memberDeviceTokenBeforeInsertHooks []MemberDeviceTokenHook
var memberDeviceTokenAfterInsertHooks []MemberDeviceTokenHook

var memberDeviceTokenBeforeUpdateHooks []MemberDeviceTokenHook
var memberDeviceTokenAfterUpdateHooks []MemberDeviceTokenHook

var memberDeviceTokenBeforeDeleteHooks []MemberDeviceTokenHook
var memberDeviceTokenAfterDeleteHooks []MemberDeviceTokenHook

var memberDeviceTokenBeforeUpsertHooks []MemberDeviceTokenHook
var memberDeviceTokenAfterUpsertHooks []MemberDeviceTokenHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *MemberDeviceToken) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range memberDeviceTokenAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *MemberDeviceToken) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range memberDeviceTokenBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *MemberDeviceToken) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range memberDeviceTokenAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *MemberDeviceToken) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range memberDeviceTokenBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *MemberDeviceToken) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range memberDeviceTokenAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *MemberDeviceToken) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range memberDeviceTokenBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *MemberDeviceToken) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range memberDeviceTokenAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *MemberDeviceToken) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range memberDeviceTokenBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *MemberDeviceToken) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range memberDeviceTokenAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddMemberDeviceTokenHook registers your hook function for all future operations.
func AddMemberDeviceTokenHook(hookPoint boil.HookPoint, memberDeviceTokenHook MemberDeviceTokenHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		memberDeviceTokenAfterSelectHooks = append(memberDeviceTokenAfterSelectHooks, memberDeviceTokenHook)
	case boil.BeforeInsertHook:
		memberDeviceTokenBeforeInsertHooks = append(memberDeviceTokenBeforeInsertHooks, memberDeviceTokenHook)
	case boil.AfterInsertHook:
		memberDeviceTokenAfterInsertHooks = append(memberDeviceTokenAfterInsertHooks, memberDeviceTokenHook)
	case boil.BeforeUpdateHook:
		memberDeviceTokenBeforeUpdateHooks = append(memberDeviceTokenBeforeUpdateHooks, memberDeviceTokenHook)
	case boil.AfterUpdateHook:
		memberDeviceTokenAfterUpdateHooks = append(memberDeviceTokenAfterUpdateHooks, memberDeviceTokenHook)
	case boil.BeforeDeleteHook:
		memberDeviceTokenBeforeDeleteHooks = append(memberDeviceTokenBeforeDeleteHooks, memberDeviceTokenHook)
	case boil.AfterDeleteHook:
		memberDeviceTokenAfterDeleteHooks = append(memberDeviceTokenAfterDeleteHooks, memberDeviceTokenHook)
	case boil.BeforeUpsertHook:
		memberDeviceTokenBeforeUpsertHooks = append(memberDeviceTokenBeforeUpsertHooks, memberDeviceTokenHook)
	case boil.AfterUpsertHook:
		memberDeviceTokenAfterUpsertHooks = append(memberDeviceTokenAfterUpsertHooks, memberDeviceTokenHook)
	}
}

// One returns a single memberDeviceToken record from the query.
func (q memberDeviceTokenQuery) One(ctx context.Context, exec boil.ContextExecutor) (*MemberDeviceToken, error) {
	o := &MemberDeviceToken{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "mysql: failed to execute a one query for member_device_token")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all MemberDeviceToken records from the query.
func (q memberDeviceTokenQuery) All(ctx context.Context, exec boil.ContextExecutor) (MemberDeviceTokenSlice, error) {
	var o []*MemberDeviceToken

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "mysql: failed to assign all query results to MemberDeviceToken slice")
	}

	if len(memberDeviceTokenAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all MemberDeviceToken records in the query.
func (q memberDeviceTokenQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "mysql: failed to count member_device_token rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q memberDeviceTokenQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "mysql: failed to check if member_device_token exists")
	}

	return count > 0, nil
}

// Member pointed to by the foreign key.
func (o *MemberDeviceToken) Member(mods ...qm.QueryMod) memberQuery {
	queryMods := []qm.QueryMod{
		qm.Where("`member_id` = ?", o.MemberID),
	}

	queryMods = append(queryMods, mods...)

	return Members(queryMods...)
}

// LoadMember allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (memberDeviceTokenL) LoadMember(ctx context.Context, e boil.ContextExecutor, singular bool, maybeMemberDeviceToken interface{}, mods queries.Applicator) error {
	var slice []*MemberDeviceToken
	var object *MemberDeviceToken

	if singular {
		var ok bool
		object, ok = maybeMemberDeviceToken.(*MemberDeviceToken)
		if !ok {
			object = new(MemberDeviceToken)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeMemberDeviceToken)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeMemberDeviceToken))
			}
		}
	} else {
		s, ok := maybeMemberDeviceToken.(*[]*MemberDeviceToken)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeMemberDeviceToken)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeMemberDeviceToken))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &memberDeviceTokenR{}
		}
		args = append(args, object.MemberID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &memberDeviceTokenR{}
			}

			for _, a := range args {
				if a == obj.MemberID {
					continue Outer
				}
			}

			args = append(args, obj.MemberID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`member`),
		qm.WhereIn(`member.member_id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Member")
	}

	var resultSlice []*Member
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Member")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for member")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for member")
	}

	if len(memberAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Member = foreign
		if foreign.R == nil {
			foreign.R = &memberR{}
		}
		foreign.R.MemberDeviceTokens = append(foreign.R.MemberDeviceTokens, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.MemberID == foreign.MemberID {
				local.R.Member = foreign
				if foreign.R == nil {
					foreign.R = &memberR{}
				}
				foreign.R.MemberDeviceTokens = append(foreign.R.MemberDeviceTokens, local)
				break
			}
		}
	}

	return nil
}

// SetMember of the memberDeviceToken to the related item.
// Sets o.R.Member to related.
// Adds o to related.R.MemberDeviceTokens.
func (o *MemberDeviceToken) SetMember(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Member) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `member_device_token` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"member_id"}),
		strmangle.WhereClause("`", "`", 0, memberDeviceTokenPrimaryKeyColumns),
	)
	values := []interface{}{related.MemberID, o.MemberDeviceTokenID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.MemberID = related.MemberID
	if o.R == nil {
		o.R = &memberDeviceTokenR{
			Member: related,
		}
	} else {
		o.R.Member = related
	}

	if related.R == nil {
		related.R = &memberR{
			MemberDeviceTokens: MemberDeviceTokenSlice{o},
		}
	} else {
		related.R.MemberDeviceTokens = append(related.R.MemberDeviceTokens, o)
	}

	return nil
}

// MemberDeviceTokens retrieves all the records using an executor.
func MemberDeviceTokens(mods ...qm.QueryMod) memberDeviceTokenQuery {
	mods = append(mods, qm.From("`member_device_token`"))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"`member_device_token`.*"})
	}

	return memberDeviceTokenQuery{q}
}

// FindMemberDeviceToken retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindMemberDeviceToken(ctx context.Context, exec boil.ContextExecutor, memberDeviceTokenID int64, selectCols ...string) (*MemberDeviceToken, error) {
	memberDeviceTokenObj := &MemberDeviceToken{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `member_device_token` where `member_device_token_id`=?", sel,
	)

	q := queries.Raw(query, memberDeviceTokenID)

	err := q.Bind(ctx, exec, memberDeviceTokenObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "mysql: unable to select from member_device_token")
	}

	if err = memberDeviceTokenObj.doAfterSelectHooks(ctx, exec); err != nil {
		return memberDeviceTokenObj, err
	}

	return memberDeviceTokenObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *MemberDeviceToken) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("mysql: no member_device_token provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(memberDeviceTokenColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	memberDeviceTokenInsertCacheMut.RLock()
	cache, cached := memberDeviceTokenInsertCache[key]
	memberDeviceTokenInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			memberDeviceTokenAllColumns,
			memberDeviceTokenColumnsWithDefault,
			memberDeviceTokenColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(memberDeviceTokenType, memberDeviceTokenMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(memberDeviceTokenType, memberDeviceTokenMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `member_device_token` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `member_device_token` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `member_device_token` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, memberDeviceTokenPrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "mysql: unable to insert into member_device_token")
	}

	var lastID int64
	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.MemberDeviceTokenID = int64(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == memberDeviceTokenMapping["member_device_token_id"] {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.MemberDeviceTokenID,
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, identifierCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "mysql: unable to populate default values for member_device_token")
	}

CacheNoHooks:
	if !cached {
		memberDeviceTokenInsertCacheMut.Lock()
		memberDeviceTokenInsertCache[key] = cache
		memberDeviceTokenInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the MemberDeviceToken.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *MemberDeviceToken) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	memberDeviceTokenUpdateCacheMut.RLock()
	cache, cached := memberDeviceTokenUpdateCache[key]
	memberDeviceTokenUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			memberDeviceTokenAllColumns,
			memberDeviceTokenPrimaryKeyColumns,
		)
		if len(wl) == 0 {
			return 0, errors.New("mysql: unable to update member_device_token, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `member_device_token` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, memberDeviceTokenPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(memberDeviceTokenType, memberDeviceTokenMapping, append(wl, memberDeviceTokenPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "mysql: unable to update member_device_token row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "mysql: failed to get rows affected by update for member_device_token")
	}

	if !cached {
		memberDeviceTokenUpdateCacheMut.Lock()
		memberDeviceTokenUpdateCache[key] = cache
		memberDeviceTokenUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q memberDeviceTokenQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "mysql: unable to update all for member_device_token")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "mysql: unable to retrieve rows affected for member_device_token")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o MemberDeviceTokenSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("mysql: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), memberDeviceTokenPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `member_device_token` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, memberDeviceTokenPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "mysql: unable to update all in memberDeviceToken slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "mysql: unable to retrieve rows affected all in update all memberDeviceToken")
	}
	return rowsAff, nil
}

var mySQLMemberDeviceTokenUniqueColumns = []string{
	"member_device_token_id",
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *MemberDeviceToken) Upsert(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("mysql: no member_device_token provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(memberDeviceTokenColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLMemberDeviceTokenUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	memberDeviceTokenUpsertCacheMut.RLock()
	cache, cached := memberDeviceTokenUpsertCache[key]
	memberDeviceTokenUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			memberDeviceTokenAllColumns,
			memberDeviceTokenColumnsWithDefault,
			memberDeviceTokenColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			memberDeviceTokenAllColumns,
			memberDeviceTokenPrimaryKeyColumns,
		)

		if !updateColumns.IsNone() && len(update) == 0 {
			return errors.New("mysql: unable to upsert member_device_token, could not build update column list")
		}

		ret := strmangle.SetComplement(memberDeviceTokenAllColumns, strmangle.SetIntersect(insert, update))

		cache.query = buildUpsertQueryMySQL(dialect, "`member_device_token`", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `member_device_token` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(memberDeviceTokenType, memberDeviceTokenMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(memberDeviceTokenType, memberDeviceTokenMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "mysql: unable to upsert for member_device_token")
	}

	var lastID int64
	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.MemberDeviceTokenID = int64(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == memberDeviceTokenMapping["member_device_token_id"] {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(memberDeviceTokenType, memberDeviceTokenMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "mysql: unable to retrieve unique values for member_device_token")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, nzUniqueCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "mysql: unable to populate default values for member_device_token")
	}

CacheNoHooks:
	if !cached {
		memberDeviceTokenUpsertCacheMut.Lock()
		memberDeviceTokenUpsertCache[key] = cache
		memberDeviceTokenUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single MemberDeviceToken record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *MemberDeviceToken) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("mysql: no MemberDeviceToken provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), memberDeviceTokenPrimaryKeyMapping)
	sql := "DELETE FROM `member_device_token` WHERE `member_device_token_id`=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "mysql: unable to delete from member_device_token")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "mysql: failed to get rows affected by delete for member_device_token")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q memberDeviceTokenQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("mysql: no memberDeviceTokenQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "mysql: unable to delete all from member_device_token")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "mysql: failed to get rows affected by deleteall for member_device_token")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o MemberDeviceTokenSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(memberDeviceTokenBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), memberDeviceTokenPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `member_device_token` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, memberDeviceTokenPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "mysql: unable to delete all from memberDeviceToken slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "mysql: failed to get rows affected by deleteall for member_device_token")
	}

	if len(memberDeviceTokenAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *MemberDeviceToken) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindMemberDeviceToken(ctx, exec, o.MemberDeviceTokenID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *MemberDeviceTokenSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := MemberDeviceTokenSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), memberDeviceTokenPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `member_device_token`.* FROM `member_device_token` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, memberDeviceTokenPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "mysql: unable to reload all in MemberDeviceTokenSlice")
	}

	*o = slice

	return nil
}

// MemberDeviceTokenExists checks if the MemberDeviceToken row exists.
func MemberDeviceTokenExists(ctx context.Context, exec boil.ContextExecutor, memberDeviceTokenID int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `member_device_token` where `member_device_token_id`=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, memberDeviceTokenID)
	}
	row := exec.QueryRowContext(ctx, sql, memberDeviceTokenID)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "mysql: unable to check if member_device_token exists")
	}

	return exists, nil
}

// Exists checks if the MemberDeviceToken row exists.
func (o *MemberDeviceToken) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return MemberDeviceTokenExists(ctx, exec, o.MemberDeviceTokenID)
}
