// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/blacklist": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "memberId를 통해 차단 목록 조회하",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Blacklist"
                ],
                "summary": "memberId를 통해 차단 목록 조회하기",
                "responses": {
                    "200": {
                        "description": "성공",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/pkg.BaseResponseStruct"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/handler.blacklistResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "memberId를 통해 차단하기",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Blacklist"
                ],
                "summary": "memberId를 통해 차단하기",
                "parameters": [
                    {
                        "description": "blacklistRequest",
                        "name": "blacklistRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.blacklistRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "성공"
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "memberId를 통해 차단해제하기",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Blacklist"
                ],
                "summary": "memberId를 통해 차단해제하기",
                "parameters": [
                    {
                        "description": "deleteBlacklistRequest",
                        "name": "deleteBlacklistRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.deleteBlacklistRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "성공"
                    }
                }
            }
        },
        "/chart": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "인기차트 조회",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Chart"
                ],
                "summary": "인기차트 조회",
                "responses": {
                    "200": {
                        "description": "성공",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/pkg.BaseResponseStruct"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/handler.TotalChartResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/comment": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "SongId에 댓글 달기",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Comment"
                ],
                "summary": "SongId에 댓글 달기",
                "parameters": [
                    {
                        "description": "commentRequest",
                        "name": "CommentRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.CommentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "성공",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/pkg.BaseResponseStruct"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/handler.CommentResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/comment/recomment/{commentId}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get reComments for a specific comment identified by commentId",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Comment"
                ],
                "summary": "Retrieve reComments for the specified CommentId",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Comment ID",
                        "name": "commentId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/pkg.BaseResponseStruct"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/handler.CommentResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/comment/report": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "해당하는 댓글ID를 통해 신고하기",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Comment"
                ],
                "summary": "해당하는 댓글ID를 통해 신고하기",
                "parameters": [
                    {
                        "description": "ReportRequest",
                        "name": "ReportRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.ReportRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "성공",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/pkg.BaseResponseStruct"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/handler.ReportResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/comment/{commentId}/like": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "해당하는 댓글에 좋아요 누르기",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Comment"
                ],
                "summary": "해당하는 댓글에 좋아요 누르기",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Comment ID",
                        "name": "commentId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "성공",
                        "schema": {
                            "$ref": "#/definitions/pkg.BaseResponseStruct"
                        }
                    }
                }
            }
        },
        "/comment/{songId}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get comments for a specific song identified by songId",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Comment"
                ],
                "summary": "Retrieve comments for the specified SongId",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Song ID",
                        "name": "songId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/pkg.BaseResponseStruct"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/handler.CommentResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/keep": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "플레이리스트에 있는 노래들을 가져온다",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Playlist"
                ],
                "summary": "플레이리스트에 노래를 가져온다",
                "responses": {
                    "200": {
                        "description": "성공",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/pkg.BaseResponseStruct"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/handler.PlaylistAddResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "노래들을 하나씩 플레이리스트에 추가한 후 적용된 플레이리스트의 노래들을 리턴한다",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Playlist"
                ],
                "summary": "플레이리스트에 노래를 추가한다",
                "parameters": [
                    {
                        "description": "노래 리스트",
                        "name": "PlaylistAddRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.PlaylistAddRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "성공",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/pkg.BaseResponseStruct"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/handler.PlaylistAddResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "노래들을 하나씩 플레이리스트에서 삭제한다",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Playlist"
                ],
                "summary": "플레이리스트에 노래를 제거한다",
                "parameters": [
                    {
                        "description": "노래 리스트",
                        "name": "SongDeleteFromPlaylistRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.SongDeleteFromPlaylistRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "성공",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/pkg.BaseResponseStruct"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/handler.PlaylistAddResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/member": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "사용자 정보 조회",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Member"
                ],
                "summary": "Member의 정보를 가져온다",
                "responses": {
                    "200": {
                        "description": "성공",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/pkg.BaseResponseStruct"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/handler.MemberResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/member/login": {
            "post": {
                "description": "IdToken을 이용한 회원가입 및 로그인",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Signup and Login"
                ],
                "summary": "회원가입 및 로그인",
                "parameters": [
                    {
                        "description": "idToken 및 Provider",
                        "name": "songs",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "성공",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/pkg.BaseResponseStruct"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/handler.LoginResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/member/logout": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "멤버 회원 로그아웃",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Member"
                ],
                "summary": "멤버 회원 로그아웃",
                "parameters": [
                    {
                        "description": "refreshToken",
                        "name": "refreshToken",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.WithdrawRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "성공",
                        "schema": {
                            "$ref": "#/definitions/pkg.BaseResponseStruct"
                        }
                    }
                }
            }
        },
        "/member/reissue": {
            "post": {
                "description": "AccessToken 재발급 및 RefreshToken 재발급 (RTR Refresh Token Rotation)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Reissue"
                ],
                "summary": "AccessToken RefreshToken 재발급",
                "parameters": [
                    {
                        "description": "accessToken 및 refreshToken",
                        "name": "songs",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.ReissueRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "성공",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/pkg.BaseResponseStruct"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/handler.LoginResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/member/withdraw": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "멤버 회원 탈퇴",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Member"
                ],
                "summary": "멤버 회원 탈퇴",
                "parameters": [
                    {
                        "description": "refreshToken",
                        "name": "refreshToken",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.WithdrawRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "성공",
                        "schema": {
                            "$ref": "#/definitions/pkg.BaseResponseStruct"
                        }
                    }
                }
            }
        },
        "/recommend/home": {
            "post": {
                "description": "태그에 해당하는 노래를 추천합니다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Recommendation"
                ],
                "summary": "[미사용] 노래 추천 by 태그",
                "parameters": [
                    {
                        "description": "태그 목록",
                        "name": "songs",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.homeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "성공",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/pkg.BaseResponseStruct"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/handler.homeResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/recommend/home/songs": {
            "get": {
                "description": "앨범 이미지와 함께 노래를 추천",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Recommendation"
                ],
                "summary": "[미사용] 노래 추천 5곡",
                "responses": {
                    "200": {
                        "description": "성공",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/pkg.BaseResponseStruct"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/handler.homeSongResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/recommend/refresh": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "태그에 해당하는 노래를 새로고침합니다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Recommendation"
                ],
                "summary": "새로고침 노래 추천",
                "parameters": [
                    {
                        "description": "태그",
                        "name": "songs",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.refreshRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "성공",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/pkg.BaseResponseStruct"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/handler.refreshResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/recommend/songs": {
            "post": {
                "description": "노래 번호 목록을 보내면 유사한 노래들을 추천합니다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Recommendation"
                ],
                "summary": "[미사용] 노래 추천 by 노래 번호 목록",
                "parameters": [
                    {
                        "description": "노래 번호 목록",
                        "name": "songs",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.songRecommendRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "성공",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/pkg.BaseResponseStruct"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/handler.songRecommendResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/search/{searchKeyword}": {
            "get": {
                "description": "노래 검색 API로, 노래 제목 또는 아티스트 이름을 검색합니다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Search"
                ],
                "summary": "노래 검색 API",
                "parameters": [
                    {
                        "type": "string",
                        "description": "검색 키워드",
                        "name": "searchKeyword",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "성공",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/pkg.BaseResponseStruct"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/handler.songSearchInfoResponses"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "실패 - 빈 리스트 반환",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/pkg.BaseResponseStruct"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/song-review-options": {
            "get": {
                "description": "노래 평가 선택지를 모두 조회합니다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Song review option CR for admin"
                ],
                "summary": "노래 평가 선택지를 모두 조회합니다.",
                "responses": {
                    "200": {
                        "description": "성공",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/pkg.BaseResponseStruct"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "type": "string"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "description": "노래 평가 선택지를 추가합니다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Song review option CR for admin"
                ],
                "summary": "노래 평가 선택지를 추가합니다.",
                "parameters": [
                    {
                        "description": "평가 선택지",
                        "name": "songReviewOptionAddRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.songReviewOptionAddRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "성공"
                    }
                }
            }
        },
        "/songs/{songId}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "노래 상세 정보를 조회합니다",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Songs"
                ],
                "summary": "노래 상세 정보를 조회합니다",
                "parameters": [
                    {
                        "type": "string",
                        "description": "songId",
                        "name": "songId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "성공",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/pkg.BaseResponseStruct"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/handler.songInfoResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/songs/{songId}/related": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "연관된 노래들과 다음 페이지 번호를 함께 조회합니다. 노래 상세 화면에 첫 진입했을 경우 page 번호는 1입니다. 무한스크롤을 진행한다면 응답에 포함되어 오는 nextPage를 다음번에 포함하여 보내면 됩니다. nextPage는 1씩 증가합니다. 더이상 노래가 없을 경우, 응답에는 빈 배열과 함께 nextPage는 1로 반환됩니다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Songs"
                ],
                "summary": "연관된 노래들을 조회합니다",
                "parameters": [
                    {
                        "type": "string",
                        "description": "songId",
                        "name": "songId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "현재 조회할 노래 목록의 쪽수. 입력하지 않는다면 기본값인 1쪽을 조회",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "한번에 조회할 노래 개수. 입력하지 않는다면 기본값인 20개씩 조회",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "성공",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/pkg.BaseResponseStruct"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/handler.relatedSongResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/songs/{songId}/reviews": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "노래 평가를 조회합니다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Songs"
                ],
                "summary": "노래 평가를 조회합니다.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "songId",
                        "name": "songId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "성공",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/pkg.BaseResponseStruct"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/handler.songReviewOptionGetResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "노래 평가를 등록/수정합니다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Songs"
                ],
                "summary": "노래 평가를 등록/수정합니다.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "songId",
                        "name": "songId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "songReviewOptionId",
                        "name": "songReview",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.songReviewOptionPutRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "성공"
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "노래 평가를 삭제합니다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Songs"
                ],
                "summary": "노래 평가를 삭제합니다.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "songId",
                        "name": "songId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "성공"
                    }
                }
            }
        },
        "/tags": {
            "get": {
                "description": "ssss 태그 목록을 조회합니다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tags"
                ],
                "summary": "ssss 태그 목록 가져오기",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg.BaseResponseStruct"
                        }
                    }
                }
            }
        },
        "/version": {
            "get": {
                "description": "등록되어 있는 모든 버전 확인 가능",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "App Version"
                ],
                "summary": "모든 버전 확인",
                "responses": {
                    "200": {
                        "description": "성공\" {object} pkg.BaseResponseStruct{data=[]versionResponse} \"성공"
                    }
                }
            }
        },
        "/version/check": {
            "post": {
                "description": "헤더에 플랫폼 정보를 포함하고, request body 앱의 버전을 보내면, 최신 버전인지 여부와 강제 업데이트 필요 여부를 응답",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "App Version"
                ],
                "summary": "버전 확인",
                "parameters": [
                    {
                        "description": "현재 앱 버전 정보",
                        "name": "version",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.versionCheckRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg.BaseResponseStruct"
                        }
                    }
                }
            }
        },
        "/version/update": {
            "post": {
                "description": "새로운 버전이 나왔을때 버전을 추가할 수 있음 (플랫폼(ios, android), 버전, 이전 버전들을 강제 업데이트 할지 여부)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "App Version"
                ],
                "summary": "버전 추가",
                "parameters": [
                    {
                        "description": "등록 버전 정보",
                        "name": "version",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.latestVersionUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "성공"
                    }
                }
            }
        }
    },
    "definitions": {
        "handler.ChartResponse": {
            "type": "object",
            "properties": {
                "artistName": {
                    "type": "string"
                },
                "isMr": {
                    "type": "integer"
                },
                "new": {
                    "type": "string"
                },
                "ranking": {
                    "type": "integer"
                },
                "rankingChange": {
                    "type": "integer"
                },
                "songId": {
                    "type": "integer"
                },
                "songName": {
                    "type": "string"
                },
                "songNumber": {
                    "type": "integer"
                },
                "totalScore": {
                    "type": "number"
                }
            }
        },
        "handler.CommentRequest": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "isRecomment": {
                    "type": "boolean"
                },
                "parentCommentId": {
                    "type": "integer"
                },
                "songId": {
                    "type": "integer"
                }
            }
        },
        "handler.CommentResponse": {
            "type": "object",
            "properties": {
                "commentId": {
                    "type": "integer"
                },
                "content": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "isLiked": {
                    "type": "boolean"
                },
                "isRecomment": {
                    "type": "boolean"
                },
                "likes": {
                    "type": "integer"
                },
                "memberId": {
                    "type": "integer"
                },
                "nickname": {
                    "type": "string"
                },
                "parentCommentId": {
                    "type": "integer"
                },
                "recomments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.CommentResponse"
                    }
                },
                "songId": {
                    "type": "integer"
                }
            }
        },
        "handler.LoginRequest": {
            "type": "object",
            "properties": {
                "birthYear": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "idToken": {
                    "type": "string"
                },
                "provider": {
                    "type": "string"
                }
            }
        },
        "handler.LoginResponse": {
            "type": "object",
            "properties": {
                "accessToken": {
                    "type": "string"
                },
                "refreshToken": {
                    "type": "string"
                }
            }
        },
        "handler.MemberResponse": {
            "type": "object",
            "properties": {
                "birthYear": {
                    "type": "integer"
                },
                "email": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string"
                }
            }
        },
        "handler.PlaylistAddRequest": {
            "type": "object",
            "properties": {
                "songId": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "handler.PlaylistAddResponse": {
            "type": "object",
            "properties": {
                "singerName": {
                    "type": "string"
                },
                "songId": {
                    "type": "integer"
                },
                "songName": {
                    "type": "string"
                },
                "songNumber": {
                    "type": "integer"
                }
            }
        },
        "handler.ReissueRequest": {
            "type": "object",
            "properties": {
                "accessToken": {
                    "type": "string"
                },
                "refreshToken": {
                    "type": "string"
                }
            }
        },
        "handler.ReportRequest": {
            "type": "object",
            "properties": {
                "commentId": {
                    "type": "integer"
                },
                "reason": {
                    "type": "string"
                },
                "subjectMemberId": {
                    "type": "integer"
                }
            }
        },
        "handler.ReportResponse": {
            "type": "object",
            "properties": {
                "commentId": {
                    "type": "integer"
                },
                "reason": {
                    "type": "string"
                },
                "reportId": {
                    "type": "integer"
                },
                "reporterId": {
                    "type": "integer"
                },
                "subjectMemberId": {
                    "type": "integer"
                }
            }
        },
        "handler.SongDeleteFromPlaylistRequest": {
            "type": "object",
            "properties": {
                "songIds": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "handler.TotalChartResponse": {
            "type": "object",
            "properties": {
                "female": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.ChartResponse"
                    }
                },
                "gender": {
                    "type": "string"
                },
                "male": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.ChartResponse"
                    }
                },
                "time": {
                    "type": "string"
                }
            }
        },
        "handler.WithdrawRequest": {
            "type": "object",
            "properties": {
                "refreshToken": {
                    "type": "string"
                }
            }
        },
        "handler.blacklistRequest": {
            "type": "object",
            "properties": {
                "memberId": {
                    "type": "integer"
                }
            }
        },
        "handler.blacklistResponse": {
            "type": "object",
            "properties": {
                "blockDate": {
                    "type": "string"
                },
                "memberId": {
                    "type": "integer"
                },
                "nickname": {
                    "type": "string"
                }
            }
        },
        "handler.deleteBlacklistRequest": {
            "type": "object",
            "properties": {
                "memberIds": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "handler.homeRequest": {
            "type": "object",
            "properties": {
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "handler.homeResponse": {
            "type": "object",
            "properties": {
                "songs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.songHomeResponse"
                    }
                },
                "tag": {
                    "type": "string"
                }
            }
        },
        "handler.homeSongResponse": {
            "type": "object",
            "properties": {
                "Album": {
                    "type": "string"
                },
                "singerName": {
                    "type": "string"
                },
                "songId": {
                    "type": "integer"
                },
                "songName": {
                    "type": "string"
                },
                "songNumber": {
                    "type": "integer"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "handler.latestVersionUpdateRequest": {
            "type": "object",
            "properties": {
                "forceUpdate": {
                    "type": "boolean"
                },
                "platform": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "handler.refreshRequest": {
            "type": "object",
            "properties": {
                "tag": {
                    "type": "string"
                }
            }
        },
        "handler.refreshResponse": {
            "type": "object",
            "properties": {
                "isKeep": {
                    "type": "boolean"
                },
                "singerName": {
                    "type": "string"
                },
                "songId": {
                    "type": "integer"
                },
                "songName": {
                    "type": "string"
                },
                "songNumber": {
                    "type": "integer"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "handler.relatedSong": {
            "type": "object",
            "properties": {
                "isKeep": {
                    "type": "boolean"
                },
                "singerName": {
                    "type": "string"
                },
                "songId": {
                    "type": "integer"
                },
                "songName": {
                    "type": "string"
                },
                "songNumber": {
                    "type": "integer"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "handler.relatedSongResponse": {
            "type": "object",
            "properties": {
                "nextPage": {
                    "type": "integer"
                },
                "songs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.relatedSong"
                    }
                }
            }
        },
        "handler.songHomeResponse": {
            "type": "object",
            "properties": {
                "album": {
                    "type": "string"
                },
                "singerName": {
                    "type": "string"
                },
                "songId": {
                    "type": "integer"
                },
                "songName": {
                    "type": "string"
                },
                "songNumber": {
                    "type": "integer"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "handler.songInfoResponse": {
            "type": "object",
            "properties": {
                "Album": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "isKeep": {
                    "type": "boolean"
                },
                "octave": {
                    "type": "string"
                },
                "singerName": {
                    "type": "string"
                },
                "songId": {
                    "type": "integer"
                },
                "songName": {
                    "type": "string"
                },
                "songNumber": {
                    "type": "integer"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "handler.songRecommendRequest": {
            "type": "object",
            "properties": {
                "songNumbers": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "handler.songRecommendResponse": {
            "type": "object",
            "properties": {
                "singerName": {
                    "type": "string"
                },
                "songName": {
                    "type": "string"
                },
                "songNumber": {
                    "type": "integer"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "handler.songReviewOptionAddRequest": {
            "type": "object",
            "properties": {
                "enum": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "handler.songReviewOptionGetResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "selected": {
                    "type": "boolean"
                },
                "songReviewOptionId": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "handler.songReviewOptionPutRequest": {
            "type": "object",
            "properties": {
                "songReviewOptionId": {
                    "type": "integer"
                }
            }
        },
        "handler.songSearchInfoResponse": {
            "type": "object",
            "properties": {
                "album": {
                    "type": "string"
                },
                "singerName": {
                    "type": "string"
                },
                "songId": {
                    "type": "integer"
                },
                "songName": {
                    "type": "string"
                },
                "songNumber": {
                    "type": "integer"
                }
            }
        },
        "handler.songSearchInfoResponses": {
            "type": "object",
            "properties": {
                "artistName": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.songSearchInfoResponse"
                    }
                },
                "songName": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.songSearchInfoResponse"
                    }
                },
                "songNumber": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.songSearchInfoResponse"
                    }
                }
            }
        },
        "handler.versionCheckRequest": {
            "type": "object",
            "properties": {
                "version": {
                    "type": "string"
                }
            }
        },
        "pkg.BaseResponseStruct": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "싱송생송 API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
