basePath: /api/v1
definitions:
  handler.HomeRequest:
    properties:
      tags:
        items:
          type: string
        type: array
    type: object
  handler.HomeResponse:
    properties:
      songs:
        items:
          $ref: '#/definitions/handler.songHomeResponse'
        type: array
      tag:
        type: string
    type: object
  handler.SongRecommendRequest:
    properties:
      songs:
        items:
          type: integer
        type: array
    type: object
  handler.SongRecommendResponse:
    properties:
      singerName:
        type: string
      songName:
        type: string
      songNumber:
        type: integer
      tags:
        items:
          type: string
        type: array
    type: object
  handler.songHomeResponse:
    properties:
      singerName:
        type: string
      songName:
        type: string
      songNumber:
        type: integer
      tags:
        items:
          type: string
        type: array
    type: object
  pkg.BaseResponseStruct:
    properties:
      data: {}
      message:
        type: string
    type: object
info:
  contact: {}
  title: 싱송생송 API
  version: "1.0"
paths:
  /recommend/home:
    post:
      consumes:
      - application/json
      description: 태그에 해당하는 노래를 추천합니다.
      parameters:
      - description: 태그 목록
        in: body
        name: songs
        required: true
        schema:
          $ref: '#/definitions/handler.HomeRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 성공
          schema:
            allOf:
            - $ref: '#/definitions/pkg.BaseResponseStruct'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/handler.HomeResponse'
                  type: array
              type: object
      summary: 노래 추천 by 태그
      tags:
      - Recommendation
  /recommend/songs:
    post:
      consumes:
      - application/json
      description: 노래 번호 목록을 보내면 유사한 노래들을 추천합니다.
      parameters:
      - description: 노래 번호 목록
        in: body
        name: songs
        required: true
        schema:
          $ref: '#/definitions/handler.SongRecommendRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 성공
          schema:
            allOf:
            - $ref: '#/definitions/pkg.BaseResponseStruct'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/handler.SongRecommendResponse'
                  type: array
              type: object
      summary: 노래 추천 by 노래 번호 목록
      tags:
      - Recommendation
  /tags:
    get:
      consumes:
      - application/json
      description: ssss 태그 목록을 조회합니다.
      produces:
      - application/json
      responses:
        "200":
          description: 성공
          schema:
            items:
              type: string
            type: array
      summary: ssss 태그 목록 가져오기
      tags:
      - Tags
swagger: "2.0"
