// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.2
// source: proto/langchainAgentRecommend/langchainAgentRecommend.proto

package langchainAgentRecommend

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	LangchainAgentRecommend_GetLangchainAgentRecommendation_FullMethodName = "/langchainAgentRecommend.LangchainAgentRecommend/GetLangchainAgentRecommendation"
)

// LangchainAgentRecommendClient is the client API for LangchainAgentRecommend service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// LangChain 서비스
type LangchainAgentRecommendClient interface {
	GetLangchainAgentRecommendation(ctx context.Context, in *LangchainAgentRequest, opts ...grpc.CallOption) (*LangchainAgentResponse, error)
}

type langchainAgentRecommendClient struct {
	cc grpc.ClientConnInterface
}

func NewLangchainAgentRecommendClient(cc grpc.ClientConnInterface) LangchainAgentRecommendClient {
	return &langchainAgentRecommendClient{cc}
}

func (c *langchainAgentRecommendClient) GetLangchainAgentRecommendation(ctx context.Context, in *LangchainAgentRequest, opts ...grpc.CallOption) (*LangchainAgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LangchainAgentResponse)
	err := c.cc.Invoke(ctx, LangchainAgentRecommend_GetLangchainAgentRecommendation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LangchainAgentRecommendServer is the server API for LangchainAgentRecommend service.
// All implementations must embed UnimplementedLangchainAgentRecommendServer
// for forward compatibility.
//
// LangChain 서비스
type LangchainAgentRecommendServer interface {
	GetLangchainAgentRecommendation(context.Context, *LangchainAgentRequest) (*LangchainAgentResponse, error)
	mustEmbedUnimplementedLangchainAgentRecommendServer()
}

// UnimplementedLangchainAgentRecommendServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLangchainAgentRecommendServer struct{}

func (UnimplementedLangchainAgentRecommendServer) GetLangchainAgentRecommendation(context.Context, *LangchainAgentRequest) (*LangchainAgentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLangchainAgentRecommendation not implemented")
}
func (UnimplementedLangchainAgentRecommendServer) mustEmbedUnimplementedLangchainAgentRecommendServer() {
}
func (UnimplementedLangchainAgentRecommendServer) testEmbeddedByValue() {}

// UnsafeLangchainAgentRecommendServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LangchainAgentRecommendServer will
// result in compilation errors.
type UnsafeLangchainAgentRecommendServer interface {
	mustEmbedUnimplementedLangchainAgentRecommendServer()
}

func RegisterLangchainAgentRecommendServer(s grpc.ServiceRegistrar, srv LangchainAgentRecommendServer) {
	// If the following call pancis, it indicates UnimplementedLangchainAgentRecommendServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LangchainAgentRecommend_ServiceDesc, srv)
}

func _LangchainAgentRecommend_GetLangchainAgentRecommendation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LangchainAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LangchainAgentRecommendServer).GetLangchainAgentRecommendation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LangchainAgentRecommend_GetLangchainAgentRecommendation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LangchainAgentRecommendServer).GetLangchainAgentRecommendation(ctx, req.(*LangchainAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LangchainAgentRecommend_ServiceDesc is the grpc.ServiceDesc for LangchainAgentRecommend service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LangchainAgentRecommend_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "langchainAgentRecommend.LangchainAgentRecommend",
	HandlerType: (*LangchainAgentRecommendServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLangchainAgentRecommendation",
			Handler:    _LangchainAgentRecommend_GetLangchainAgentRecommendation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/langchainAgentRecommend/langchainAgentRecommend.proto",
}
