name: Go

on:
  push:
    branches: [ "feature/#3" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Build
        run: go build -v ./...

  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:latest
          platforms: linux/amd64,linux/arm64

      - name: Docker logout
        run: docker logout

  deploy:
    runs-on: ubuntu-latest
    needs: docker

    steps:
      - name: Pull Docker image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:latest

      - name: Run Docker container
        run: docker run -d -p 8080:8080 \
          --env PINECONE_API_KEY=${{ secrets.PINECONE_API_KEY }} \
          --env PINECONE_INDEX=${{ secrets.PINECONE_INDEX }} \
          --env DB_HOST=${{ secrets.DB_HOST }} \
          --env DB_PORT=${{ secrets.DB_PORT }} \
          --env DB_NAME=${{ secrets.DB_NAME }} \
          --env DB_USER=${{ secrets.DB_USER }} \
          --env DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
          ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:latest